


When('hago click en la opcion {string}') do |string|
    if string == "Cursos"
        page.find("#post-1024 > div > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-724e068e.elementor-section-full_width.elementor-section-height-min-height.elementor-section-stretched.elementor-section-height-default.elementor-section-items-middle > div.elementor-container.elementor-column-gap-wide > div > div.elementor-column.elementor-col-50.elementor-top-column.elementor-element.elementor-element-6a2eae92 > div > div > section > div.elementor-container.elementor-column-gap-default > div > div.elementor-column.elementor-col-33.elementor-inner-column.elementor-element.elementor-element-72f92542 > div > div > div > div > div > div.elementor-cta__content").click
      elsif string == "Eventos"
        page.find("#post-1024 > div > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-724e068e.elementor-section-full_width.elementor-section-height-min-height.elementor-section-stretched.elementor-section-height-default.elementor-section-items-middle > div.elementor-container.elementor-column-gap-wide > div > div.elementor-column.elementor-col-50.elementor-top-column.elementor-element.elementor-element-6a2eae92 > div > div > section > div.elementor-container.elementor-column-gap-default > div > div.elementor-column.elementor-col-33.elementor-inner-column.elementor-element.elementor-element-3cfe5088 > div > div > div > div > div > div.elementor-cta__content").click
      elsif string == "Experiencias"
        page.find("#post-1024 > div > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-724e068e.elementor-section-full_width.elementor-section-height-min-height.elementor-section-stretched.elementor-section-height-default.elementor-section-items-middle > div.elementor-container.elementor-column-gap-wide > div > div.elementor-column.elementor-col-50.elementor-top-column.elementor-element.elementor-element-6a2eae92 > div > div > section > div.elementor-container.elementor-column-gap-default > div > div.elementor-column.elementor-col-33.elementor-inner-column.elementor-element.elementor-element-276a69c2 > div > div > div > div > div > div.elementor-cta__content").click
      end
  end
  
  Then('me encuentro en la pagina de {string}') do |string|
    if string == "Cursos"
        page.find("#post-1024 > div > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-724e068e.elementor-section-full_width.elementor-section-height-min-height.elementor-section-stretched.elementor-section-height-default.elementor-section-items-middle > div.elementor-container.elementor-column-gap-wide > div > div.elementor-column.elementor-col-50.elementor-top-column.elementor-element.elementor-element-6a2eae92 > div > div > section > div.elementor-container.elementor-column-gap-default > div > div.elementor-column.elementor-col-33.elementor-inner-column.elementor-element.elementor-element-72f92542 > div > div > div > div > div > div.elementor-cta__content").click
      elsif string == "Eventos"
        page.find("#post-1024 > div > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-724e068e.elementor-section-full_width.elementor-section-height-min-height.elementor-section-stretched.elementor-section-height-default.elementor-section-items-middle > div.elementor-container.elementor-column-gap-wide > div > div.elementor-column.elementor-col-50.elementor-top-column.elementor-element.elementor-element-6a2eae92 > div > div > section > div.elementor-container.elementor-column-gap-default > div > div.elementor-column.elementor-col-33.elementor-inner-column.elementor-element.elementor-element-3cfe5088 > div > div > div > div > div > div.elementor-cta__content").click
      elsif string == "Experiencias"
        page.find("#post-1024 > div > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-724e068e.elementor-section-full_width.elementor-section-height-min-height.elementor-section-stretched.elementor-section-height-default.elementor-section-items-middle > div.elementor-container.elementor-column-gap-wide > div > div.elementor-column.elementor-col-50.elementor-top-column.elementor-element.elementor-element-6a2eae92 > div > div > section > div.elementor-container.elementor-column-gap-default > div > div.elementor-column.elementor-col-33.elementor-inner-column.elementor-element.elementor-element-276a69c2 > div > div > div > div > div > div.elementor-cta__content").click
      end
  end